### ISSUE TITLE
Section: Cannot move first section down or up to first section in list

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#209] opened 2016-08-02 14:40 UTC
For data set sections, when trying to move a section to the top of the list, or moving the top section down in the list, it fails with "Failed to move section".

It should be possible to move the top section down / move sections to the top of the list.

![move](https://cloud.githubusercontent.com/assets/908206/17332668/d54882fe-58cf-11e6-907c-bb375e481d1a.png)

**Comment by nicolayr** [comment] 2016-08-19 16:15
This happens because the Immunization and Nutrition sections both have sort order = 0 in the database ([cfr](https://play.dhis2.org/dev/api/dataSets/BfMAe6Itzgt.json?fields=sections[displayName,sortOrder])), so it's actually a data consistency problem and not a bug in the maintenance app.

@larshelge - should we add functionality for fixing this kind of problem?

**Comment by Markionium** [comment] 2016-08-19 18:38
@nicolayr @larshelge I think this should be fixed in the database, having the sort order contain identical numbers should not happen imo.

**Closed** 2016-10-03 11:07 UTC
Labels: bug
