### ISSUE TITLE
Jumping to next input field using tab does not work on date fields

### ISSUE THREAD

**Issue by janhenrikoverland** [dhis2/maintenance-app#146] opened 2016-05-04 18:16 UTC
Steps to reproduce:

- Create a new organisation unit
- Focus on "Name" input field
- Use tab to jump to the next fields

-> On "Opening date", elements on the top of the page are focused instead. So you're not able to tab through the whole form.

**Comment by Markionium** [comment] 2016-05-04 18:24
Thnx @janhenrikoverland bjorn found this during the testing. Closing this as a duplicate of https://github.com/dhis2/maintenance-app/issues/100

**Closed by Markionium** 2016-05-04 18:24 UTC
Labels: form, priority:low
