### ISSUE TITLE
Linked meta-data

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#40] opened 2016-02-20 21:59 UTC
Placeholder. Requires more objects to be included in the maintenance app.

Provide links to related objects in the add/edit screens. This includes:

Data element > option set.
Data element > legend set.

**Comment by Markionium** [comment] 2016-07-20 10:56
This is related/a duplicate of #133

Since #133 has a better description i am closing this one.

**Closed by Markionium** 2016-07-20 10:56 UTC
Labels: enhancement, help wanted, question
