### ISSUE TITLE
Indicator numerator: Rename to org unit counts

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#213] opened 2016-08-05 16:58 UTC
In the indicator numerator screen, rename "Organisation unit counts" to "Org unit counts". This to save real estate as the header is getting crammed.

![org](https://cloud.githubusercontent.com/assets/908206/17444130/a9f4b476-5b3e-11e6-819b-435ae0b87d94.png)

**Comment by jason-p-pickering** [comment] 2016-08-05 17:01
Not really useful solution, as it may not be applicable to all languages.

**Comment by Markionium** [comment] 2016-08-05 17:03
This is a duplicate of https://github.com/dhis2/maintenance-app/issues/172

**Closed by Markionium** 2016-08-05 17:03 UTC
Labels: enhancement
